// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	"hello-shorturl-go/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/shorten",
			Handler: shortenHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/expand",
			Handler: expandHandler(serverCtx),
		},
	})
}
