// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package main

import (
	"flag"
	"fmt"
	"log"

	"hello-shorturl-go/rpc/transform/internal/config"
	"hello-shorturl-go/rpc/transform/internal/server"
	"hello-shorturl-go/rpc/transform/internal/svc"
	transform "hello-shorturl-go/rpc/transform/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/rpcx"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/transform.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	transformerSrv := server.NewTransformerServer(ctx)

	s, err := rpcx.NewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		transform.RegisterTransformerServer(grpcServer, transformerSrv)
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
